### PR TITLE
Wr/upstream changes

### PR DESCRIPTION
**Pull request by willrax**
bring in upstream changes

### CODE REVIEW

**Comment by willrax** [comment]
@Arkham do you mind taking a look see?

**Comment by Arkham** [comment]
@willrax any way we can get rid of this port? :(

**Comment by willrax** [comment]
we can try to merge our changes in.

**Comment by brianstorti** [comment]
Not really sure why we forked this instead of trying to add these changes (that seems to be pretty minimal) to the gem. But for now I think it's ok to merge this (assuming it does't break anything :)

**Comment by willrax** [comment]
i think its because of the keyword manage, which isn't a typical type of action

**Pull request closed without merging**
